// megafunction wizard: %ALTCLKCTRL%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altclkctrl 

// ============================================================
// File Name: clk_global.v
// Megafunction Name(s):
// 			altclkctrl
//
// Simulation Library Files(s):
// 			arriaii
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 11.1 Build 173 11/01/2011 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2011 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altclkctrl CBX_AUTO_BLACKBOX="ALL" CLOCK_TYPE="Global Clock" DEVICE_FAMILY="Arria II GX" USE_GLITCH_FREE_SWITCH_OVER_IMPLEMENTATION="ON" clkselect ena inclk outclk
//VERSION_BEGIN 11.1 cbx_altclkbuf 2011:10:31:21:13:12:SJ cbx_cycloneii 2011:10:31:21:13:13:SJ cbx_lpm_add_sub 2011:10:31:21:13:13:SJ cbx_lpm_compare 2011:10:31:21:13:13:SJ cbx_lpm_decode 2011:10:31:21:13:13:SJ cbx_lpm_mux 2011:10:31:21:13:13:SJ cbx_mgl 2011:10:31:21:15:34:SJ cbx_stratix 2011:10:31:21:13:14:SJ cbx_stratixii 2011:10:31:21:13:14:SJ cbx_stratixiii 2011:10:31:21:13:14:SJ cbx_stratixv 2011:10:31:21:13:14:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = clkctrl 1 reg 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  clk_global_altclkctrl_9bf
	( 
	clkselect,
	ena,
	inclk,
	outclk) /* synthesis synthesis_clearbox=2 */;
	input   [1:0]  clkselect;
	input   ena;
	input   [3:0]  inclk;
	output   outclk;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  clkselect;
	tri1   ena;
	tri0   [3:0]  inclk;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	[1:0]	select_reg;
	wire  wire_sd1_enaout;
	wire  wire_sd1_outclk;
	wire  wire_sd2_outclk;
	wire  [1:0]  clkselect_wire;
	wire  [3:0]  inclk_wire;
	wire  [1:0]  select_enable_wire;

	// synopsys translate_off
	initial
		select_reg = 0;
	// synopsys translate_on
	always @ ( posedge wire_sd2_outclk)
		if (wire_sd1_enaout == 1'b0)   select_reg <= clkselect_wire[1:0];
	arriaii_clkena   sd1
	( 
	.ena((ena & (~ select_enable_wire[1]))),
	.enaout(wire_sd1_enaout),
	.inclk(wire_sd2_outclk),
	.outclk(wire_sd1_outclk)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		sd1.clock_type = "Global Clock",
		sd1.ena_register_mode = "falling edge",
		sd1.lpm_type = "arriaii_clkena";
	arriaii_clkselect   sd2
	( 
	.clkselect({select_reg}),
	.inclk(inclk_wire),
	.outclk(wire_sd2_outclk));
	assign
		clkselect_wire = {clkselect},
		inclk_wire = {inclk},
		outclk = wire_sd1_outclk,
		select_enable_wire = {(select_enable_wire[0] | (clkselect_wire[1] ^ select_reg[1])), (clkselect_wire[0] ^ select_reg[0])};
endmodule //clk_global_altclkctrl_9bf
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module clk_global (
	clkselect,
	inclk0x,
	inclk1x,
	inclk2x,
	inclk3x,
	outclk)/* synthesis synthesis_clearbox = 2 */;

	input	[1:0]  clkselect;
	input	  inclk0x;
	input	  inclk1x;
	input	  inclk2x;
	input	  inclk3x;
	output	  outclk;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0	[1:0]  clkselect;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  sub_wire0;
	wire  sub_wire1 = 1'h1;
	wire  sub_wire6 = inclk3x;
	wire  sub_wire5 = inclk2x;
	wire  sub_wire4 = inclk1x;
	wire  outclk = sub_wire0;
	wire  sub_wire2 = inclk0x;
	wire [3:0] sub_wire3 = {sub_wire6, sub_wire5, sub_wire4, sub_wire2};

	clk_global_altclkctrl_9bf	clk_global_altclkctrl_9bf_component (
				.clkselect (clkselect),
				.ena (sub_wire1),
				.inclk (sub_wire3),
				.outclk (sub_wire0))/* synthesis synthesis_clearbox=2
	 clearbox_macroname = altclkctrl
	 clearbox_defparam = "intended_device_family=Arria II GX;use_glitch_free_switch_over_implementation=ON;clock_type=Global Clock;" */;

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Arria II GX"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: PRIVATE: clock_inputs NUMERIC "4"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Arria II GX"
// Retrieval info: CONSTANT: USE_GLITCH_FREE_SWITCH_OVER_IMPLEMENTATION STRING "ON"
// Retrieval info: CONSTANT: clock_type STRING "Global Clock"
// Retrieval info: USED_PORT: clkselect 0 0 2 0 INPUT GND "clkselect[1..0]"
// Retrieval info: USED_PORT: inclk0x 0 0 0 0 INPUT NODEFVAL "inclk0x"
// Retrieval info: USED_PORT: inclk1x 0 0 0 0 INPUT NODEFVAL "inclk1x"
// Retrieval info: USED_PORT: inclk2x 0 0 0 0 INPUT NODEFVAL "inclk2x"
// Retrieval info: USED_PORT: inclk3x 0 0 0 0 INPUT NODEFVAL "inclk3x"
// Retrieval info: USED_PORT: outclk 0 0 0 0 OUTPUT NODEFVAL "outclk"
// Retrieval info: CONNECT: @clkselect 0 0 2 0 clkselect 0 0 2 0
// Retrieval info: CONNECT: @ena 0 0 0 0 VCC 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 0 inclk0x 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 1 inclk1x 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 2 inclk2x 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 3 inclk3x 0 0 0 0
// Retrieval info: CONNECT: outclk 0 0 0 0 @outclk 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL clk_global.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL clk_global.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL clk_global.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL clk_global.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL clk_global_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL clk_global_bb.v FALSE
// Retrieval info: LIB_FILE: arriaii
